# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TelaPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 770)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 770))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 770))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Logo login/6c4ab934-5734-4488-a80c-3c41e43d4df3.jfif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1000, 770))
        self.centralwidget.setStyleSheet("color: rgb(255, 255, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Painelsuperior = QtWidgets.QFrame(self.centralwidget)
        self.Painelsuperior.setMinimumSize(QtCore.QSize(0, 170))
        self.Painelsuperior.setMaximumSize(QtCore.QSize(16777215, 170))
        self.Painelsuperior.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.Painelsuperior.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Painelsuperior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Painelsuperior.setObjectName("Painelsuperior")
        self.verticalLayout.addWidget(self.Painelsuperior)
        self.fundo = QtWidgets.QFrame(self.centralwidget)
        self.fundo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fundo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fundo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fundo.setObjectName("fundo")
        self.gridLayout = QtWidgets.QGridLayout(self.fundo)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_4 = QtWidgets.QFrame(self.fundo)
        self.frame_4.setMinimumSize(QtCore.QSize(300, 336))
        self.frame_4.setMaximumSize(QtCore.QSize(300, 336))
        self.frame_4.setStyleSheet("image: url(:/Logo login/43443.png);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout.addWidget(self.frame_4, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.pushButton_5 = QtWidgets.QPushButton(self.fundo)
        self.pushButton_5.setMinimumSize(QtCore.QSize(450, 90))
        self.pushButton_5.setMaximumSize(QtCore.QSize(450, 90))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    font: 11pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid;\n"
"    border-color: rgb(70, 70, 70);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(255, 0, 0);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 1, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.fundo)
        self.pushButton_6.setMinimumSize(QtCore.QSize(450, 90))
        self.pushButton_6.setMaximumSize(QtCore.QSize(450, 90))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    font: 11pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid;\n"
"    border-color: rgb(70, 70, 70);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(255, 0, 0);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 1, 1, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.fundo)
        self.frame_5.setMinimumSize(QtCore.QSize(300, 336))
        self.frame_5.setMaximumSize(QtCore.QSize(300, 336))
        self.frame_5.setStyleSheet("image: url(:/Logo login/pencilandpaper_102621.png);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout.addWidget(self.frame_5, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.fundo)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tela Principal"))
        self.pushButton_5.setText(_translate("MainWindow", "Consultar paciênte"))
        self.pushButton_6.setText(_translate("MainWindow", "Criar Ficha do paciênte"))
import Imag_rc
