# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'triagemcerta.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1011, 808)
        MainWindow.setMinimumSize(QtCore.QSize(1011, 808))
        MainWindow.setMaximumSize(QtCore.QSize(1011, 808))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Logo login/6c4ab934-5734-4488-a80c-3c41e43d4df3.jfif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1000, 808))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.superior = QtWidgets.QFrame(self.centralwidget)
        self.superior.setMaximumSize(QtCore.QSize(16777215, 170))
        self.superior.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.superior.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.superior.setObjectName("superior")
        self.verticalLayout.addWidget(self.superior)
        self.fundo = QtWidgets.QFrame(self.centralwidget)
        self.fundo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fundo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fundo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fundo.setObjectName("fundo")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fundo)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.principaldireito = QtWidgets.QFrame(self.fundo)
        self.principaldireito.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.principaldireito.setFrameShadow(QtWidgets.QFrame.Raised)
        self.principaldireito.setObjectName("principaldireito")
        self.frame_4 = QtWidgets.QFrame(self.principaldireito)
        self.frame_4.setGeometry(QtCore.QRect(10, 148, 593, 480))
        self.frame_4.setMinimumSize(QtCore.QSize(593, 480))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 480))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setGeometry(QtCore.QRect(9, 9, 271, 200))
        self.frame_6.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_12.setGeometry(QtCore.QRect(50, 27, 171, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_13.setGeometry(QtCore.QRect(50, 69, 171, 20))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_14.setGeometry(QtCore.QRect(60, 111, 160, 20))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_15.setGeometry(QtCore.QRect(85, 153, 133, 20))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.label_16 = QtWidgets.QLabel(self.frame_6)
        self.label_16.setGeometry(QtCore.QRect(11, 27, 27, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame_6)
        self.label_17.setGeometry(QtCore.QRect(11, 69, 26, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.frame_6)
        self.label_18.setGeometry(QtCore.QRect(11, 111, 36, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame_6)
        self.label_19.setGeometry(QtCore.QRect(11, 153, 68, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.frame_6)
        self.label_20.setGeometry(QtCore.QRect(10, -3, 47, 13))
        self.label_20.setObjectName("label_20")
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setGeometry(QtCore.QRect(9, 215, 575, 200))
        self.frame_7.setMinimumSize(QtCore.QSize(575, 200))
        self.frame_7.setMaximumSize(QtCore.QSize(575, 200))
        self.frame_7.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_8.setGeometry(QtCore.QRect(412, 90, 151, 20))
        self.lineEdit_8.setMaxLength(11)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_2.setGeometry(QtCore.QRect(64, 20, 501, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_3.setGeometry(QtCore.QRect(64, 55, 279, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_6.setGeometry(QtCore.QRect(412, 55, 151, 20))
        self.lineEdit_6.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_6.setMaxLength(11)
        self.lineEdit_6.setReadOnly(False)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_7.setGeometry(QtCore.QRect(75, 90, 268, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_3 = QtWidgets.QLabel(self.frame_7)
        self.label_3.setGeometry(QtCore.QRect(27, 20, 31, 20))
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(self.frame_7)
        self.label_7.setGeometry(QtCore.QRect(27, 55, 31, 20))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_7)
        self.label_8.setGeometry(QtCore.QRect(10, 90, 61, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_7)
        self.label_9.setGeometry(QtCore.QRect(380, 55, 21, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_7)
        self.label_10.setGeometry(QtCore.QRect(360, 90, 41, 16))
        self.label_10.setObjectName("label_10")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_9.setGeometry(QtCore.QRect(64, 125, 501, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_10.setGeometry(QtCore.QRect(64, 160, 271, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_11.setGeometry(QtCore.QRect(392, 160, 171, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_11 = QtWidgets.QLabel(self.frame_7)
        self.label_11.setGeometry(QtCore.QRect(11, 125, 47, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_7)
        self.label_12.setGeometry(QtCore.QRect(11, 160, 47, 16))
        self.label_12.setObjectName("label_12")
        self.label_14 = QtWidgets.QLabel(self.frame_7)
        self.label_14.setGeometry(QtCore.QRect(350, 160, 41, 16))
        self.label_14.setObjectName("label_14")
        self.label_13 = QtWidgets.QLabel(self.frame_7)
        self.label_13.setGeometry(QtCore.QRect(10, -3, 71, 16))
        self.label_13.setObjectName("label_13")
        self.checkBox_16 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox_16.setGeometry(QtCore.QRect(94, -2, 70, 17))
        self.checkBox_16.setObjectName("checkBox_16")
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        self.frame_8.setGeometry(QtCore.QRect(9, 421, 575, 50))
        self.frame_8.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.checkBox_11 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox_11.setGeometry(QtCore.QRect(11, 11, 106, 17))
        self.checkBox_11.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox_12.setGeometry(QtCore.QRect(123, 11, 106, 17))
        self.checkBox_12.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_13 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox_13.setGeometry(QtCore.QRect(235, 11, 105, 17))
        self.checkBox_13.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_14 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox_14.setGeometry(QtCore.QRect(346, 11, 106, 17))
        self.checkBox_14.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_15 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox_15.setGeometry(QtCore.QRect(458, 11, 91, 17))
        self.checkBox_15.setMinimumSize(QtCore.QSize(91, 17))
        self.checkBox_15.setMaximumSize(QtCore.QSize(91, 17))
        self.checkBox_15.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.checkBox_15.setObjectName("checkBox_15")
        self.label_2 = QtWidgets.QLabel(self.frame_8)
        self.label_2.setGeometry(QtCore.QRect(20, -3, 47, 13))
        self.label_2.setObjectName("label_2")
        self.frame_11 = QtWidgets.QFrame(self.frame_4)
        self.frame_11.setGeometry(QtCore.QRect(318, 0, 271, 211))
        self.frame_11.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.frame_12 = QtWidgets.QFrame(self.frame_11)
        self.frame_12.setGeometry(QtCore.QRect(0, 3, 160, 100))
        self.frame_12.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.checkBox_25 = QtWidgets.QCheckBox(self.frame_12)
        self.checkBox_25.setGeometry(QtCore.QRect(11, 20, 138, 11))
        self.checkBox_25.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.checkBox_25.setObjectName("checkBox_25")
        self.checkBox_26 = QtWidgets.QCheckBox(self.frame_12)
        self.checkBox_26.setGeometry(QtCore.QRect(11, 35, 138, 11))
        self.checkBox_26.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.checkBox_26.setObjectName("checkBox_26")
        self.checkBox_27 = QtWidgets.QCheckBox(self.frame_12)
        self.checkBox_27.setGeometry(QtCore.QRect(11, 50, 138, 11))
        self.checkBox_27.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.checkBox_27.setObjectName("checkBox_27")
        self.checkBox_28 = QtWidgets.QCheckBox(self.frame_12)
        self.checkBox_28.setGeometry(QtCore.QRect(11, 65, 138, 11))
        self.checkBox_28.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.checkBox_28.setObjectName("checkBox_28")
        self.label_33 = QtWidgets.QLabel(self.frame_12)
        self.label_33.setGeometry(QtCore.QRect(10, -4, 91, 16))
        self.label_33.setObjectName("label_33")
        self.checkBox_45 = QtWidgets.QCheckBox(self.frame_12)
        self.checkBox_45.setGeometry(QtCore.QRect(11, 80, 138, 11))
        self.checkBox_45.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.checkBox_45.setObjectName("checkBox_45")
        self.frame_13 = QtWidgets.QFrame(self.frame_11)
        self.frame_13.setGeometry(QtCore.QRect(160, 3, 101, 101))
        self.frame_13.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_34 = QtWidgets.QLabel(self.frame_13)
        self.label_34.setGeometry(QtCore.QRect(6, -5, 31, 16))
        self.label_34.setObjectName("label_34")
        self.checkBox_29 = QtWidgets.QCheckBox(self.frame_13)
        self.checkBox_29.setGeometry(QtCore.QRect(11, 13, 81, 17))
        self.checkBox_29.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.checkBox_29.setObjectName("checkBox_29")
        self.checkBox_30 = QtWidgets.QCheckBox(self.frame_13)
        self.checkBox_30.setGeometry(QtCore.QRect(11, 35, 70, 17))
        self.checkBox_30.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.checkBox_30.setObjectName("checkBox_30")
        self.checkBox_31 = QtWidgets.QCheckBox(self.frame_13)
        self.checkBox_31.setGeometry(QtCore.QRect(11, 55, 81, 17))
        self.checkBox_31.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.checkBox_31.setObjectName("checkBox_31")
        self.checkBox_32 = QtWidgets.QCheckBox(self.frame_13)
        self.checkBox_32.setGeometry(QtCore.QRect(11, 75, 70, 17))
        self.checkBox_32.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.checkBox_32.setObjectName("checkBox_32")
        self.label_35 = QtWidgets.QLabel(self.frame_11)
        self.label_35.setGeometry(QtCore.QRect(10, 112, 47, 13))
        self.label_35.setObjectName("label_35")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit_24.setGeometry(QtCore.QRect(60, 110, 201, 20))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.label_30 = QtWidgets.QLabel(self.frame_11)
        self.label_30.setGeometry(QtCore.QRect(10, 140, 101, 16))
        self.label_30.setObjectName("label_30")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.frame_11)
        self.dateEdit_2.setGeometry(QtCore.QRect(120, 140, 110, 22))
        self.dateEdit_2.setAccelerated(False)
        self.dateEdit_2.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.dateEdit_2.setProperty("showGroupSeparator", False)
        self.dateEdit_2.setCalendarPopup(False)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.frame_9 = QtWidgets.QFrame(self.principaldireito)
        self.frame_9.setGeometry(QtCore.QRect(18, 9, 581, 141))
        self.frame_9.setMinimumSize(QtCore.QSize(581, 141))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_9.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_16.setGeometry(QtCore.QRect(89, 32, 475, 20))
        self.lineEdit_16.setMinimumSize(QtCore.QSize(475, 0))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_17.setGeometry(QtCore.QRect(89, 58, 171, 20))
        self.lineEdit_17.setMinimumSize(QtCore.QSize(171, 20))
        self.lineEdit_17.setMaximumSize(QtCore.QSize(171, 20))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_21 = QtWidgets.QLabel(self.frame_9)
        self.label_21.setGeometry(QtCore.QRect(10, 32, 76, 20))
        self.label_21.setMinimumSize(QtCore.QSize(70, 20))
        self.label_21.setMaximumSize(QtCore.QSize(76, 16777215))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.frame_9)
        self.label_22.setGeometry(QtCore.QRect(12, 58, 70, 20))
        self.label_22.setMinimumSize(QtCore.QSize(70, 20))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.frame_9)
        self.label_23.setGeometry(QtCore.QRect(12, 84, 70, 20))
        self.label_23.setMinimumSize(QtCore.QSize(70, 20))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.frame_9)
        self.label_24.setGeometry(QtCore.QRect(12, 110, 70, 20))
        self.label_24.setMinimumSize(QtCore.QSize(70, 20))
        self.label_24.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.frame_9)
        self.label_25.setGeometry(QtCore.QRect(12, -5, 41, 16))
        self.label_25.setObjectName("label_25")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_18.setGeometry(QtCore.QRect(89, 84, 171, 20))
        self.lineEdit_18.setMinimumSize(QtCore.QSize(171, 20))
        self.lineEdit_18.setMaximumSize(QtCore.QSize(171, 16777215))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_19.setGeometry(QtCore.QRect(89, 110, 171, 20))
        self.lineEdit_19.setMinimumSize(QtCore.QSize(171, 0))
        self.lineEdit_19.setMaximumSize(QtCore.QSize(171, 16777215))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_20.setGeometry(QtCore.QRect(323, 110, 85, 20))
        self.lineEdit_20.setMinimumSize(QtCore.QSize(85, 20))
        self.lineEdit_20.setMaximumSize(QtCore.QSize(85, 16777215))
        self.lineEdit_20.setText("")
        self.lineEdit_20.setMaxLength(11)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.label_26 = QtWidgets.QLabel(self.frame_9)
        self.label_26.setGeometry(QtCore.QRect(283, 110, 25, 20))
        self.label_26.setMinimumSize(QtCore.QSize(25, 20))
        self.label_26.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_26.setObjectName("label_26")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_21.setGeometry(QtCore.QRect(323, 84, 85, 20))
        self.lineEdit_21.setMinimumSize(QtCore.QSize(85, 20))
        self.lineEdit_21.setMaximumSize(QtCore.QSize(85, 16777215))
        self.lineEdit_21.setText("")
        self.lineEdit_21.setMaxLength(7)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.label_27 = QtWidgets.QLabel(self.frame_9)
        self.label_27.setGeometry(QtCore.QRect(283, 84, 25, 20))
        self.label_27.setMinimumSize(QtCore.QSize(25, 20))
        self.label_27.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.frame_9)
        self.label_28.setGeometry(QtCore.QRect(423, 84, 33, 20))
        self.label_28.setMinimumSize(QtCore.QSize(33, 20))
        self.label_28.setMaximumSize(QtCore.QSize(33, 16777215))
        self.label_28.setObjectName("label_28")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_22.setGeometry(QtCore.QRect(471, 84, 85, 20))
        self.lineEdit_22.setMinimumSize(QtCore.QSize(85, 20))
        self.lineEdit_22.setMaximumSize(QtCore.QSize(85, 16777215))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.label_29 = QtWidgets.QLabel(self.frame_9)
        self.label_29.setGeometry(QtCore.QRect(423, 110, 31, 20))
        self.label_29.setMinimumSize(QtCore.QSize(31, 20))
        self.label_29.setObjectName("label_29")
        self.label_31 = QtWidgets.QLabel(self.frame_9)
        self.label_31.setGeometry(QtCore.QRect(273, 58, 47, 13))
        self.label_31.setObjectName("label_31")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_23.setGeometry(QtCore.QRect(323, 58, 240, 20))
        self.lineEdit_23.setMinimumSize(QtCore.QSize(221, 20))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_25.setGeometry(QtCore.QRect(471, 110, 85, 20))
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_26.setGeometry(QtCore.QRect(90, 8, 475, 20))
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.label_32 = QtWidgets.QLabel(self.frame_9)
        self.label_32.setGeometry(QtCore.QRect(12, 13, 61, 13))
        self.label_32.setMaximumSize(QtCore.QSize(16777215, 13))
        self.label_32.setObjectName("label_32")
        self.horizontalLayout.addWidget(self.principaldireito)
        self.principalesquerdo = QtWidgets.QFrame(self.fundo)
        self.principalesquerdo.setMinimumSize(QtCore.QSize(0, 0))
        self.principalesquerdo.setMaximumSize(QtCore.QSize(400, 16777215))
        self.principalesquerdo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.principalesquerdo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.principalesquerdo.setObjectName("principalesquerdo")
        self.frame = QtWidgets.QFrame(self.principalesquerdo)
        self.frame.setGeometry(QtCore.QRect(10, 420, 379, 200))
        self.frame.setMaximumSize(QtCore.QSize(380, 200))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.ultimamovimentao = QtWidgets.QFrame(self.frame)
        self.ultimamovimentao.setMinimumSize(QtCore.QSize(181, 92))
        self.ultimamovimentao.setMaximumSize(QtCore.QSize(181, 92))
        self.ultimamovimentao.setFrameShape(QtWidgets.QFrame.Box)
        self.ultimamovimentao.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ultimamovimentao.setObjectName("ultimamovimentao")
        self.label_4 = QtWidgets.QLabel(self.ultimamovimentao)
        self.label_4.setGeometry(QtCore.QRect(11, 30, 36, 16))
        self.label_4.setObjectName("label_4")
        self.dateEdit_4 = QtWidgets.QDateEdit(self.ultimamovimentao)
        self.dateEdit_4.setGeometry(QtCore.QRect(55, 49, 115, 16))
        self.dateEdit_4.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.dateEdit_4.setCalendarPopup(False)
        self.dateEdit_4.setObjectName("dateEdit_4")
        self.hora_4 = QtWidgets.QLabel(self.ultimamovimentao)
        self.hora_4.setGeometry(QtCore.QRect(11, 68, 23, 16))
        self.hora_4.setObjectName("hora_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.ultimamovimentao)
        self.lineEdit_4.setGeometry(QtCore.QRect(55, 30, 115, 16))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.timeEdit_4 = QtWidgets.QTimeEdit(self.ultimamovimentao)
        self.timeEdit_4.setGeometry(QtCore.QRect(55, 68, 51, 16))
        self.timeEdit_4.setCalendarPopup(False)
        self.timeEdit_4.setObjectName("timeEdit_4")
        self.DAta_4 = QtWidgets.QLabel(self.ultimamovimentao)
        self.DAta_4.setGeometry(QtCore.QRect(11, 49, 23, 16))
        self.DAta_4.setObjectName("DAta_4")
        self.entrada_4 = QtWidgets.QLabel(self.ultimamovimentao)
        self.entrada_4.setGeometry(QtCore.QRect(11, -5, 101, 16))
        self.entrada_4.setMaximumSize(QtCore.QSize(101, 16))
        self.entrada_4.setObjectName("entrada_4")
        self.gridLayout.addWidget(self.ultimamovimentao, 1, 1, 1, 1)
        self.painelentrada = QtWidgets.QFrame(self.frame)
        self.painelentrada.setMinimumSize(QtCore.QSize(181, 92))
        self.painelentrada.setMaximumSize(QtCore.QSize(181, 92))
        self.painelentrada.setFrameShape(QtWidgets.QFrame.Box)
        self.painelentrada.setFrameShadow(QtWidgets.QFrame.Raised)
        self.painelentrada.setObjectName("painelentrada")
        self.dateEdit = QtWidgets.QDateEdit(self.painelentrada)
        self.dateEdit.setGeometry(QtCore.QRect(55, 49, 115, 16))
        self.dateEdit.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.dateEdit.setCalendarPopup(False)
        self.dateEdit.setObjectName("dateEdit")
        self.timeEdit = QtWidgets.QTimeEdit(self.painelentrada)
        self.timeEdit.setGeometry(QtCore.QRect(55, 68, 51, 16))
        self.timeEdit.setCalendarPopup(False)
        self.timeEdit.setObjectName("timeEdit")
        self.DAta = QtWidgets.QLabel(self.painelentrada)
        self.DAta.setGeometry(QtCore.QRect(11, 49, 23, 16))
        self.DAta.setObjectName("DAta")
        self.hora = QtWidgets.QLabel(self.painelentrada)
        self.hora.setGeometry(QtCore.QRect(11, 68, 23, 16))
        self.hora.setObjectName("hora")
        self.entrada = QtWidgets.QLabel(self.painelentrada)
        self.entrada.setGeometry(QtCore.QRect(11, -5, 38, 16))
        self.entrada.setMaximumSize(QtCore.QSize(41, 16))
        self.entrada.setObjectName("entrada")
        self.lineEdit = QtWidgets.QLineEdit(self.painelentrada)
        self.lineEdit.setGeometry(QtCore.QRect(55, 30, 115, 16))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.painelentrada)
        self.label.setGeometry(QtCore.QRect(11, 30, 36, 16))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.painelentrada, 0, 0, 1, 1)
        self.PAINELSAIDA = QtWidgets.QFrame(self.frame)
        self.PAINELSAIDA.setMinimumSize(QtCore.QSize(181, 92))
        self.PAINELSAIDA.setMaximumSize(QtCore.QSize(181, 92))
        self.PAINELSAIDA.setFrameShape(QtWidgets.QFrame.Box)
        self.PAINELSAIDA.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PAINELSAIDA.setObjectName("PAINELSAIDA")
        self.dateEdit_saida = QtWidgets.QDateEdit(self.PAINELSAIDA)
        self.dateEdit_saida.setGeometry(QtCore.QRect(58, 35, 79, 18))
        self.dateEdit_saida.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.dateEdit_saida.setCalendarPopup(False)
        self.dateEdit_saida.setObjectName("dateEdit_saida")
        self.hora_saida = QtWidgets.QLabel(self.PAINELSAIDA)
        self.hora_saida.setGeometry(QtCore.QRect(11, 60, 23, 16))
        self.hora_saida.setObjectName("hora_saida")
        self.timeEdit_saida = QtWidgets.QTimeEdit(self.PAINELSAIDA)
        self.timeEdit_saida.setGeometry(QtCore.QRect(58, 60, 51, 18))
        self.timeEdit_saida.setCalendarPopup(False)
        self.timeEdit_saida.setObjectName("timeEdit_saida")
        self.DAtasaida = QtWidgets.QLabel(self.PAINELSAIDA)
        self.DAtasaida.setGeometry(QtCore.QRect(11, 35, 23, 16))
        self.DAtasaida.setObjectName("DAtasaida")
        self.saida = QtWidgets.QLabel(self.PAINELSAIDA)
        self.saida.setGeometry(QtCore.QRect(12, -4, 38, 16))
        self.saida.setMaximumSize(QtCore.QSize(41, 16))
        self.saida.setObjectName("saida")
        self.gridLayout.addWidget(self.PAINELSAIDA, 0, 1, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setMinimumSize(QtCore.QSize(181, 50))
        self.frame_5.setMaximumSize(QtCore.QSize(181, 50))
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_5.setGeometry(QtCore.QRect(11, 28, 159, 16))
        self.lineEdit_5.setMinimumSize(QtCore.QSize(0, 16))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(16777215, 16))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setGeometry(QtCore.QRect(11, 11, 159, 16))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.frame_5, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.principalesquerdo)
        self.frame_2.setGeometry(QtCore.QRect(10, 308, 379, 100))
        self.frame_2.setMaximumSize(QtCore.QSize(380, 100))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.checkBox = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox.setGeometry(QtCore.QRect(10, 14, 70, 17))
        self.checkBox.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 41, 101, 17))
        self.checkBox_2.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 68, 91, 17))
        self.checkBox_3.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_4.setGeometry(QtCore.QRect(193, 14, 70, 17))
        self.checkBox_4.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_5.setGeometry(QtCore.QRect(193, 41, 70, 17))
        self.checkBox_5.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_6.setGeometry(QtCore.QRect(193, 68, 70, 17))
        self.checkBox_6.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.checkBox_6.setObjectName("checkBox_6")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(9, -4, 71, 16))
        self.label_6.setObjectName("label_6")
        self.frame_3 = QtWidgets.QFrame(self.principalesquerdo)
        self.frame_3.setGeometry(QtCore.QRect(227, 195, 160, 100))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.checkBox_7 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_7.setGeometry(QtCore.QRect(11, 11, 138, 16))
        self.checkBox_7.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_8.setGeometry(QtCore.QRect(11, 32, 138, 16))
        self.checkBox_8.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_9.setGeometry(QtCore.QRect(11, 53, 138, 16))
        self.checkBox_9.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_10.setGeometry(QtCore.QRect(11, 74, 138, 16))
        self.checkBox_10.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.checkBox_10.setObjectName("checkBox_10")
        self.label_15 = QtWidgets.QLabel(self.frame_3)
        self.label_15.setGeometry(QtCore.QRect(10, -4, 101, 14))
        self.label_15.setObjectName("label_15")
        self.frame_14 = QtWidgets.QFrame(self.principalesquerdo)
        self.frame_14.setGeometry(QtCore.QRect(4, 30, 380, 150))
        self.frame_14.setMinimumSize(QtCore.QSize(380, 150))
        self.frame_14.setMaximumSize(QtCore.QSize(380, 150))
        self.frame_14.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.checkBox_33 = QtWidgets.QCheckBox(self.frame_14)
        self.checkBox_33.setGeometry(QtCore.QRect(11, 19, 72, 17))
        self.checkBox_33.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.checkBox_33.setObjectName("checkBox_33")
        self.checkBox_34 = QtWidgets.QCheckBox(self.frame_14)
        self.checkBox_34.setGeometry(QtCore.QRect(11, 50, 91, 17))
        self.checkBox_34.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.checkBox_34.setObjectName("checkBox_34")
        self.checkBox_35 = QtWidgets.QCheckBox(self.frame_14)
        self.checkBox_35.setGeometry(QtCore.QRect(11, 81, 121, 17))
        self.checkBox_35.setMinimumSize(QtCore.QSize(11, 0))
        self.checkBox_35.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.checkBox_35.setObjectName("checkBox_35")
        self.checkBox_36 = QtWidgets.QCheckBox(self.frame_14)
        self.checkBox_36.setGeometry(QtCore.QRect(11, 112, 71, 17))
        self.checkBox_36.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.checkBox_36.setObjectName("checkBox_36")
        self.checkBox_37 = QtWidgets.QCheckBox(self.frame_14)
        self.checkBox_37.setGeometry(QtCore.QRect(134, 19, 81, 17))
        self.checkBox_37.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.checkBox_37.setObjectName("checkBox_37")
        self.checkBox_38 = QtWidgets.QCheckBox(self.frame_14)
        self.checkBox_38.setGeometry(QtCore.QRect(134, 50, 81, 17))
        self.checkBox_38.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.checkBox_38.setObjectName("checkBox_38")
        self.checkBox_39 = QtWidgets.QCheckBox(self.frame_14)
        self.checkBox_39.setGeometry(QtCore.QRect(134, 81, 91, 17))
        self.checkBox_39.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.checkBox_39.setObjectName("checkBox_39")
        self.checkBox_40 = QtWidgets.QCheckBox(self.frame_14)
        self.checkBox_40.setGeometry(QtCore.QRect(134, 112, 81, 17))
        self.checkBox_40.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.checkBox_40.setObjectName("checkBox_40")
        self.checkBox_41 = QtWidgets.QCheckBox(self.frame_14)
        self.checkBox_41.setGeometry(QtCore.QRect(255, 19, 61, 17))
        self.checkBox_41.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.checkBox_41.setObjectName("checkBox_41")
        self.checkBox_42 = QtWidgets.QCheckBox(self.frame_14)
        self.checkBox_42.setGeometry(QtCore.QRect(255, 50, 91, 17))
        self.checkBox_42.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.checkBox_42.setObjectName("checkBox_42")
        self.checkBox_43 = QtWidgets.QCheckBox(self.frame_14)
        self.checkBox_43.setGeometry(QtCore.QRect(255, 81, 91, 17))
        self.checkBox_43.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.checkBox_43.setObjectName("checkBox_43")
        self.checkBox_44 = QtWidgets.QCheckBox(self.frame_14)
        self.checkBox_44.setGeometry(QtCore.QRect(255, 112, 81, 17))
        self.checkBox_44.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.checkBox_44.setObjectName("checkBox_44")
        self.label_36 = QtWidgets.QLabel(self.frame_14)
        self.label_36.setGeometry(QtCore.QRect(10, -4, 91, 16))
        self.label_36.setObjectName("label_36")
        self.horizontalLayout.addWidget(self.principalesquerdo)
        self.verticalLayout.addWidget(self.fundo)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Nova Triagem"))
        self.label_16.setText(_translate("MainWindow", "Nome"))
        self.label_17.setText(_translate("MainWindow", "Setor"))
        self.label_18.setText(_translate("MainWindow", "Plantão"))
        self.label_19.setText(_translate("MainWindow", "Indentificação"))
        self.label_20.setText(_translate("MainWindow", "  Medico"))
        self.label_3.setText(_translate("MainWindow", "Nome"))
        self.label_7.setText(_translate("MainWindow", "RG"))
        self.label_8.setText(_translate("MainWindow", "  Parentesco"))
        self.label_9.setText(_translate("MainWindow", "CPF"))
        self.label_10.setText(_translate("MainWindow", "Telefone"))
        self.label_11.setText(_translate("MainWindow", "Endereço"))
        self.label_12.setText(_translate("MainWindow", "Bairro"))
        self.label_14.setText(_translate("MainWindow", "Cidade"))
        self.label_13.setText(_translate("MainWindow", " Responsavel"))
        self.checkBox_16.setText(_translate("MainWindow", "O Mesmo"))
        self.checkBox_11.setText(_translate("MainWindow", "Alta"))
        self.checkBox_12.setText(_translate("MainWindow", "Internação"))
        self.checkBox_13.setText(_translate("MainWindow", "Transferido"))
        self.checkBox_14.setText(_translate("MainWindow", "Óbito"))
        self.checkBox_15.setText(_translate("MainWindow", "Evasão"))
        self.label_2.setText(_translate("MainWindow", "  Destino "))
        self.checkBox_25.setText(_translate("MainWindow", "Preto"))
        self.checkBox_26.setText(_translate("MainWindow", "Branca"))
        self.checkBox_27.setText(_translate("MainWindow", "Pardo"))
        self.checkBox_28.setText(_translate("MainWindow", "indígenas"))
        self.label_33.setText(_translate("MainWindow", "Etinia do Paciente"))
        self.checkBox_45.setText(_translate("MainWindow", "Mulato"))
        self.label_34.setText(_translate("MainWindow", " Sexo"))
        self.checkBox_29.setText(_translate("MainWindow", "Masculino"))
        self.checkBox_30.setText(_translate("MainWindow", "Feminino"))
        self.checkBox_31.setText(_translate("MainWindow", "Não-Binario"))
        self.checkBox_32.setText(_translate("MainWindow", "Trans"))
        self.label_35.setText(_translate("MainWindow", "Telefone"))
        self.label_30.setText(_translate("MainWindow", "Data De Nascimento"))
        self.label_21.setText(_translate("MainWindow", "Motivo Da vinda"))
        self.label_22.setText(_translate("MainWindow", "Setor"))
        self.label_23.setText(_translate("MainWindow", "Plantão"))
        self.label_24.setText(_translate("MainWindow", "Indentificação"))
        self.label_25.setText(_translate("MainWindow", "Paciente"))
        self.label_26.setText(_translate("MainWindow", "CPF"))
        self.label_27.setText(_translate("MainWindow", "RG"))
        self.label_28.setText(_translate("MainWindow", "TP.San."))
        self.label_29.setText(_translate("MainWindow", "Idade"))
        self.label_31.setText(_translate("MainWindow", "Endereço"))
        self.label_32.setText(_translate("MainWindow", "Nome"))
        self.label_4.setText(_translate("MainWindow", "Usuário"))
        self.hora_4.setText(_translate("MainWindow", "Hora"))
        self.DAta_4.setText(_translate("MainWindow", "Data"))
        self.entrada_4.setText(_translate("MainWindow", "Ultima Movimentação"))
        self.DAta.setText(_translate("MainWindow", "Data"))
        self.hora.setText(_translate("MainWindow", "Hora"))
        self.entrada.setText(_translate("MainWindow", "Entrada"))
        self.label.setText(_translate("MainWindow", "Usuário"))
        self.hora_saida.setText(_translate("MainWindow", "Hora"))
        self.DAtasaida.setText(_translate("MainWindow", "Data"))
        self.saida.setText(_translate("MainWindow", "Saída"))
        self.label_5.setText(_translate("MainWindow", "Nº Atestado"))
        self.checkBox.setText(_translate("MainWindow", "Externo"))
        self.checkBox_2.setText(_translate("MainWindow", "Outro hospital"))
        self.checkBox_3.setText(_translate("MainWindow", "Consultório"))
        self.checkBox_4.setText(_translate("MainWindow", "PAM"))
        self.checkBox_5.setText(_translate("MainWindow", "UBS"))
        self.checkBox_6.setText(_translate("MainWindow", "Outros"))
        self.label_6.setText(_translate("MainWindow", " Prodecência"))
        self.checkBox_7.setText(_translate("MainWindow", "Consulta"))
        self.checkBox_8.setText(_translate("MainWindow", "Interconsulta"))
        self.checkBox_9.setText(_translate("MainWindow", "Emergência"))
        self.checkBox_10.setText(_translate("MainWindow", "Ambulatório"))
        self.label_15.setText(_translate("MainWindow", "Tipo de Atendimento"))
        self.checkBox_33.setText(_translate("MainWindow", "Emergêcia"))
        self.checkBox_34.setText(_translate("MainWindow", "Ambulatório"))
        self.checkBox_35.setText(_translate("MainWindow", "Farmácia Hospitalar"))
        self.checkBox_36.setText(_translate("MainWindow", "Pediatria"))
        self.checkBox_37.setText(_translate("MainWindow", "Radiologia"))
        self.checkBox_38.setText(_translate("MainWindow", "Ortopedia"))
        self.checkBox_39.setText(_translate("MainWindow", "Dermatologia"))
        self.checkBox_40.setText(_translate("MainWindow", "Psiquiatria"))
        self.checkBox_41.setText(_translate("MainWindow", "Geral"))
        self.checkBox_42.setText(_translate("MainWindow", "Oftalmologia"))
        self.checkBox_43.setText(_translate("MainWindow", "Odotologia"))
        self.checkBox_44.setText(_translate("MainWindow", "Neurologia"))
        self.label_36.setText(_translate("MainWindow", "  Encaminhamento"))
import Imag_rc
